package com.hnnd.entity;

import com.hnnd.base.BaseEntity;
import com.hnnd.enums.FlagEnum;
import com.hnnd.enums.StatusEnum;

public class Major extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbg.generated
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.status
     *
     * @mbg.generated
     */
    private  StatusEnum status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.flag
     *
     * @mbg.generated
     */
    private FlagEnum flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.details
     *
     * @mbg.generated
     */
    private String details;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.name
     *
     * @return the value of major.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.name
     *
     * @param name the value for major.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.status
     *
     * @return the value of major.status
     *
     * @mbg.generated
     */
    public StatusEnum getStatus() {
        return status;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.status
     *
     * @param status the value for major.status
     *
     * @mbg.generated
     */
    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.flag
     *
     * @return the value of major.flag
     *
     * @mbg.generated
     */
    public FlagEnum getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.flag
     *
     * @param flag the value for major.flag
     *
     * @mbg.generated
     */
    public void setFlag(FlagEnum flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_area
     *
     * @return the value of major.major_area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_area
     *
     * @param majorArea the value for major.major_area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.details
     *
     * @return the value of major.details
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.details
     *
     * @param details the value for major.details
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}