package com.hnnd.dao;

import com.hnnd.entity.Major;
import java.util.List;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated
     */
    Major selectByPrimaryKey(Integer majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated
     */
    List<Major> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Major record);
}