package com.hnnd.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.major_id
     *
     * @mbg.generated
     */
    private String majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.kind
     *
     * @mbg.generated
     */
    private Integer kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.book
     *
     * @mbg.generated
     */
    private String book;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credits
     *
     * @mbg.generated
     */
    private Integer credits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseFee
     *
     * @mbg.generated
     */
    private Double coursefee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.major_id
     *
     * @return the value of course.major_id
     *
     * @mbg.generated
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.major_id
     *
     * @param majorId the value for course.major_id
     *
     * @mbg.generated
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.kind
     *
     * @return the value of course.kind
     *
     * @mbg.generated
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.kind
     *
     * @param kind the value for course.kind
     *
     * @mbg.generated
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.book
     *
     * @return the value of course.book
     *
     * @mbg.generated
     */
    public String getBook() {
        return book;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.book
     *
     * @param book the value for course.book
     *
     * @mbg.generated
     */
    public void setBook(String book) {
        this.book = book == null ? null : book.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credits
     *
     * @return the value of course.credits
     *
     * @mbg.generated
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credits
     *
     * @param credits the value for course.credits
     *
     * @mbg.generated
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseFee
     *
     * @return the value of course.courseFee
     *
     * @mbg.generated
     */
    public Double getCoursefee() {
        return coursefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseFee
     *
     * @param coursefee the value for course.courseFee
     *
     * @mbg.generated
     */
    public void setCoursefee(Double coursefee) {
        this.coursefee = coursefee;
    }
}