package com.hnnd.entity;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_id
     *
     * @mbg.generated
     */
    private Integer majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_name
     *
     * @mbg.generated
     */
    private String majorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_status
     *
     * @mbg.generated
     */
    private Integer majorStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_area
     *
     * @mbg.generated
     */
    private String majorArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_id
     *
     * @return the value of major.major_id
     *
     * @mbg.generated
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_id
     *
     * @param majorId the value for major.major_id
     *
     * @mbg.generated
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_name
     *
     * @return the value of major.major_name
     *
     * @mbg.generated
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_name
     *
     * @param majorName the value for major.major_name
     *
     * @mbg.generated
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_status
     *
     * @return the value of major.major_status
     *
     * @mbg.generated
     */
    public Integer getMajorStatus() {
        return majorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_status
     *
     * @param majorStatus the value for major.major_status
     *
     * @mbg.generated
     */
    public void setMajorStatus(Integer majorStatus) {
        this.majorStatus = majorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.delete_flag
     *
     * @return the value of major.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.delete_flag
     *
     * @param deleteFlag the value for major.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_area
     *
     * @return the value of major.major_area
     *
     * @mbg.generated
     */
    public String getMajorArea() {
        return majorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_area
     *
     * @param majorArea the value for major.major_area
     *
     * @mbg.generated
     */
    public void setMajorArea(String majorArea) {
        this.majorArea = majorArea == null ? null : majorArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.details
     *
     * @return the value of major.details
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.details
     *
     * @param details the value for major.details
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}